### PR TITLE
Add "structure" property to core properties list

### PR DESCRIPTION
**Pull request by NSoiffer**

### CODE REVIEW

**Comment by dginev** [comment]
The [recorded group consensus](https://github.com/w3c/mathml/issues/492#issuecomment-2099519349) was to name this property `:literal`, unfortunate as it may be.

**Comment by NSoiffer** [comment]
From the[ Sept 19 meeting minutes](https://lists.w3.org/Archives/Public/www-math/2024Sep/0014.html):

> DG: Was there a property to read things how they are visually written?
> 
> DC: We've got a structured property here.
> 
> NS: This means do not assume any math for anything, just read what is there.
> 
> BM: That's kind of what we're haggling about for array.
> 
> BM: This is a way to provide a default speech output. Structure is
> overridden by intent.
> 
> NS: Does that mean that if you put a structure, if you put parentheses
> around a table, put a structure property on it. I should stop saying the
> matrix for it.
> 
> DG: We should specify what structure does.
> 
> DC structure not in spec.
> 
> *ACTION:* NS: We added a :structure property which tells the system to
> simply read what is there issue 492
> <https://github.com/w3c/mathml/issues/492>. This property needs to be added
> to the list of core properties and the spec. DC: put need spec update. NS
> will update the spec.
> 
> NS: You would want to put structure up high in the description.
> 
> NS Structure literally read what is there.
> 
> NS would prefer literal to structure.
> 
> DC literal is already used so stick with structure.

But as you point out [thanks for noticing!] (which I didn't look at after reading the action item), the actual issue says that on May 2, we voted and on the name and went with "literal". I'll bring this up at the next meeting :-(

FYI: I remembered I did a name change in MathCAT a while back. Github says it was 5 months ago I and I changed `:structure` to `:literal`. I see the Swedish and Finnish translations didn't get that change because they were in a branch back then and not part of main. I need to work on a tool that spots differences between the English and other languages, but ignores actual speech....

**Comment by NSoiffer** [comment]
@dginev: I'm going to merge this so we can have a discussion of not just about the name, but also the content. Given that the group in May choose literal, I suspect I'll need to change this, but at least there will be some text to potentially discuss also.

**Comment by dginev** [comment]
@NSoiffer I am happy to offer a PR renaming these to the consensus name before this week's meeting if you have time constraints. Let me know.

**Pull request merged**
