### PR TITLE
Update to Jan 18 meeting decisions

### PR DESCRIPTION
**Pull request by NSoiffer**

### CODE REVIEW

**Comment by NSoiffer** [comment]
I think I need to take a tutorial on using forks, but this shouldn't have conflicts -- I updated before I made changes.

@davidcarlisle: can you resolve them -- I scanned through and you should just take all the incoming ones.

Thanks.

**Comment by dginev** [comment]
@NSoiffer I have been productively using `git rebase` as my primary workflow for what appears to be a decade now. There are many tutorials online, this is a reasonable recent one:
https://simondosda.github.io/posts/2022-01-03-git-rebase-workflow.html

I've been burned by diverging forks using merge back in the SVN days, and even though git does it substantially better, you can still rewrite history without realizing it. 

The rebase pain points are a little different, but they tend to mostly come up with long-lived branches that have strayed too far away from the mainline history. And a squash allows to avoid most of that pain as well (and github makes squashing easy from the UI here). For short-lived branches rebase works quite reliably.

**Comment by davidcarlisle** [comment]
@NSoiffer  git is happy, you might want to check that you are

**Comment by davidcarlisle** [comment]
@NSoiffer  

https://w3c.github.io/mathml-docs/intent-core-concepts/#calculus

has lost its first column, presumably a yaml glitch I'll sort out locally

**Pull request merged**
